# Generated by Django 2.2.20 on 2021-06-02 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='status',
            field=models.CharField(default=0, max_length=1, verbose_name='status'),
        ),
    ]
